FROM rust:buster as builder
WORKDIR app
COPY . .
RUN cargo build --release

FROM debian:buster as runtime
COPY --from=builder /app/target/release/webdav /usr/local/bin
ENTRYPOINT ["./usr/local/bin/webdav"]
